[project]
name = "real-time-team-messenger-backend"
version = "0.1.0"
description = "Real-Time Team Messenger backend"
readme = "README.md"
authors = [
    { name = "Radmir", email = "galiullinradmir17@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "passlib>=1.7.4",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.1",
]

[project.scripts]
app = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "app"
