"""add email field, change primary key to email_action_token

Revision ID: 8fcc3f2ae61a
Revises: 53c79bdbd6d6
Create Date: 2026-09-05 12:17:59.315307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcc3f2ae61a'
down_revision: Union[str, Sequence[str], None] = '53c79bdbd6d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_actions_tokens', sa.Column('email', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(op.f('email_actions_tokens_token_hash_key'), 'email_actions_tokens', type_='unique')
    op.drop_constraint(op.f('email_actions_tokens_user_id_fkey'), 'email_actions_tokens', type_='foreignkey')
    op.drop_column('email_actions_tokens', 'user_id')
    op.drop_column('email_actions_tokens', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_actions_tokens', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('email_actions_tokens', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('email_actions_tokens_user_id_fkey'), 'email_actions_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'email_actions_tokens', type_='unique')
    op.create_unique_constraint(op.f('email_actions_tokens_token_hash_key'), 'email_actions_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_column('email_actions_tokens', 'email')
    # ### end Alembic commands ###
